[package]
name = "hkml"
version = "0.1.0"
description = "Commandline tool for manipulating data from hk-modding/hk-modlinks"
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
hk_modlinks = { workspace = true, features = ["changelog", "changelog-template"] }

clap = { version = "4.4.11", features = ["derive"] }
fs_extra = "1.3.0"
itertools = "0.12.0"
serde = { version = "1.0.190", features = ["derive"] }
sha2 = "0.10.8"
toml = "0.8.8"

[features]
default = ["xml", "json"]

xml = ["hk_modlinks/xml"]
json = ["hk_modlinks/json"]
toml = ["hk_modlinks/toml"]
yaml = ["hk_modlinks/yaml"]
ron = ["hk_modlinks/ron"]
