[package]
name = "hkml"
version = "0.1.0"
description = "Commandline tool for manipulating data from hk-modding/hk-modlinks"
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
hk_modlinks = { workspace = true, features = ["all-formats", "changelog", "changelog-template"] }
clap = { version = "4.3.0", features = ["derive"] }
